---
# vars file for change_password
- name: 비밀번호 변경
  ansible.builtin.user:
    name: "{{ account }}"
    update_password: always
    password: "{{ change_password | password_hash('sha512') }}"
  notify: changed password